# SPDX-License-Identifier: LGPL-3.0-or-later
# Author: Kristian Lytje

# Embeds a set of wgsl shaders into a generated C++ source file, so no shader files have to be
# shipped alongside the binaries. Invoked in script mode:
#	cmake -DOUTPUT=<file> "-DNAMES=name1;name2" "-DFILES=file1;file2" -P embed_shaders.cmake
# The generated file defines ausaxs::gpu::shader::source::<name> for each entry, as declared in
# include/gpu/gpu/WebGPU/shaders/ShaderSource.h.

list(LENGTH NAMES _name_count)
list(LENGTH FILES _file_count)
if (NOT _name_count EQUAL _file_count)
	message(FATAL_ERROR "embed_shaders: NAMES and FILES must have the same length (got ${_name_count} and ${_file_count}).")
endif()

set(_content "// Generated by embed_shaders.cmake. Do not edit; edit the .wgsl sources instead.\n")
string(APPEND _content "#include <gpu/WebGPU/shaders/ShaderSource.h>\n\n")

math(EXPR _last "${_name_count} - 1")
foreach (_i RANGE ${_last})
	list(GET NAMES ${_i} _name)
	list(GET FILES ${_i} _file)
	file(READ ${_file} _source)
	if (_source MATCHES "\\)WGSL\"")
		message(FATAL_ERROR "embed_shaders: ${_file} contains the raw string delimiter )WGSL\".")
	endif()
	string(APPEND _content "const std::string_view ausaxs::gpu::shader::source::${_name} = R\"WGSL(\n${_source})WGSL\";\n\n")
endforeach()

file(WRITE ${OUTPUT} "${_content}")
