// SPDX-License-Identifier: LGPL-3.0-or-later
// Author: Kristian Lytje

#pragma once

#include <data/symmetry/ISymmetry.h>

#include <memory>

namespace ausaxs::symmetry {
    /**
     * @brief A nested symmetry: the {original + copies} set of an inner symmetry is treated
     *        as a single rigid unit that an outer symmetry then replicates.
     *
     * Example "p2-3": an inner p2 gives a body its dimer partner, and an outer c3 replicates
     * the dimer three-fold, yielding six copies {A,A',B,B',C,C'}.
     *
     * Copy `rep` (1-based) decodes to (outer copy k, inner copy j) via
     *   rep = k*(1 + inner->repetitions()) + j
     * and is generated by composing the two sub-transforms, outer after inner.
     */
    struct CompositeSymmetry : public ISymmetry {
        CompositeSymmetry(std::unique_ptr<ISymmetry> inner, std::unique_ptr<ISymmetry> outer);

        ISymmetry& add(observer_ptr<const ISymmetry> other) override;
        std::function<Vector3<double>(Vector3<double>)> get_transform(const Vector3<double>& cm, int rep = 1) const override;
        std::unique_ptr<ISymmetry> clone() const override;
        unsigned int repetitions() const override;
        bool is_closed() const override;

        // a composite has two parameter sets, which cannot be expressed as one contiguous
        // span; the refinement pipeline recurses into inner/outer instead (see TransformStrategy)
        std::span<double> span_translation() override;
        std::span<double> span_rotation() override;
        std::vector<SymmetricDuplicatePair> internal_pair_schedule() const override;

        std::unique_ptr<ISymmetry> inner;
        std::unique_ptr<ISymmetry> outer;
    };
}
