// SPDX-License-Identifier: LGPL-3.0-or-later
// Author: Kristian Lytje

#pragma once

#include <data/symmetry/IPolyhedralSymmetry.h>

namespace ausaxs::symmetry {
    /**
     * @brief Chiral dihedral point group D_n (order 2n).
     *
     * Generated by a C_n rotation about the principal axis and a C_2 rotation about an axis
     * perpendicular to it, yielding n rotations about the principal axis plus n perpendicular
     * two-fold flips. That perpendicularity is what distinguishes D_n from the cyclic C_2n: two
     * rotations about a *shared* axis would merely generate C_2n, whereas the perpendicular flip
     * enforces the relation s r s = r^-1 that makes the group dihedral.
     *
     * Like the polyhedral groups it is a finite rotation group about a single centre, so it reuses
     * the IPolyhedralSymmetry machinery unchanged: the 6-DOF centre offset + frame orientation, the
     * fixed group-element list, and — the entire point of the exercise — the distance-reuse pair
     * schedule that lets the SAXS backend evaluate one representative per equal-distance class.
     */
    class DihedralSymmetry final : public IPolyhedralSymmetry {
        public:
            explicit DihedralSymmetry(int n);
            std::unique_ptr<ISymmetry> clone() const override;

        private:
            const GroupData& group() const override;

            // group data depends only on n and is immutable; computed once in the constructor
            GroupData data;
    };
}
