// SPDX-License-Identifier: LGPL-3.0-or-later
// Author: Kristian Lytje

#pragma once

#include <data/symmetry/IPolyhedralSymmetry.h>

namespace ausaxs::symmetry {
    /**
     * @brief Chiral dihedral point group D_n (order 2n).
     *
     * Generated by a C_n rotation about the principal axis and a C_2 rotation about an axis
     * perpendicular to it, yielding n rotations about the principal axis plus n perpendicular
     * two-fold flips. 
     */
    class DihedralSymmetry : public IPolyhedralSymmetry {
        public:
            explicit DihedralSymmetry(int n);
            std::unique_ptr<ISymmetry> clone() const override;

        protected:
            const GroupData& group() const override;

            // group data depends only on n and is immutable; computed once in the constructor
            GroupData data;
    };
}
