if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_histogram_manager_mt_ff_grid-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_histogram_manager_mt_ff_grid-558dc3e_tests.cmake")
else()
  add_test(ftest_histogram_manager_mt_ff_grid_NOT_BUILT-558dc3e ftest_histogram_manager_mt_ff_grid_NOT_BUILT-558dc3e)
endif()
