if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_residue_map-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_residue_map-558dc3e_tests.cmake")
else()
  add_test(ftest_residue_map_NOT_BUILT-558dc3e ftest_residue_map_NOT_BUILT-558dc3e)
endif()
