if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_basis_3d-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_basis_3d-558dc3e_tests.cmake")
else()
  add_test(ftest_basis_3d_NOT_BUILT-558dc3e ftest_basis_3d_NOT_BUILT-558dc3e)
endif()
