if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_existing_file-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/feature/ftest_existing_file-558dc3e_tests.cmake")
else()
  add_test(ftest_existing_file_NOT_BUILT-558dc3e ftest_existing_file_NOT_BUILT-558dc3e)
endif()
