// SPDX-License-Identifier: LGPL-3.0-or-later
// Author: Kristian Lytje

#include <data/symmetry/ISymmetry.h>

using namespace ausaxs::symmetry;

AffineTransform ISymmetry::_get_transform(const Vector3<double>& cm, int rep) const {
    return _make_transform(_transform_anchor(cm), rep);
}

AffineTransform ISymmetry::_get_transform(
    const Vector3<double>& cm, const std::optional<Matrix<double>>& body_orientation, int rep
) const {
    auto c = _transform_anchor(cm);
    auto orientation = _transform_orientation(body_orientation);
    if (!orientation.has_value()) {return _make_transform(c, rep);}

    // the parameters live in the frame the body had when the symmetry was defined, so the copy is generated by rotating the body back into
    // that frame, applying the symmetry there, and rotating the result back out again: v -> F*(t(F^-1*(v - c) + c) - c) + c.
    // Both maps are affine, so the whole chain collapses into a single rotation and translation here rather than at every point transformed.
    const auto& F = orientation.value();
    auto t = _make_transform(c, rep);

    AffineTransform out;
    out.rotation = F*t.rotation*F.transpose();
    out.translation = c + F*(t.rotation*c + t.translation - c) - out.rotation*c;
    return out;
}

ausaxs::Vector3<double> ISymmetry::_transform_anchor(const Vector3<double>& cm) const {
    return cm;
}

std::optional<ausaxs::Matrix<double>> ISymmetry::_transform_orientation(const std::optional<Matrix<double>>& body_orientation) const {
    return body_orientation;
}

ausaxs::Vector3<double> ISymmetry::rotation_from_angle(double angle, const Vector3<double>& direction) const {
    return angle*direction;
}

std::vector<SymmetricDuplicatePair> ISymmetry::internal_pair_schedule() const {
    // Cyclic-chain reuse. With R = repetitions(), the bodies are {original, copy_1, ..., copy_R}.
    // Copy k sits one fixed generator step from copy k-1, so the distance between two bodies
    // depends only on their index separation s. In an open chain there are (R+1-s) pairs at
    // separation s; in a closed chain (the (R+1)-th step lands back on the original) separations
    // s and (R+1-s) coincide, which the +1 on the first entry and the reduced loop bound encode.
    std::vector<SymmetricDuplicatePair> out;
    bool closed = is_closed();
    int reps = static_cast<int>(repetitions());

    // a closed 2-body symmetry (e.g. a 180-degree c2) is a special case: the cycle has a single
    // distinct pair, since the wrap-around pair {copy, original} coincides with {original, copy}
    if (closed && reps == 1) {
        out.push_back({0, 1, 1});
        return out;
    }

    for (int k = 0; k < reps - static_cast<int>(closed); ++k) {
        int scale = reps - k;
        if (k == 0 && closed) {scale += 1;}
        out.push_back({0, k+1, scale});
    }
    return out;
}
