# CMake generated Testfile for 
# Source directory: /home/runner/work/AUSAXS/AUSAXS/tests/unit
# Build directory: /home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_atom-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_body-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_signaller-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_state_manager-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_symmetry-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_dataset-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_dataset_2d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_named_dataset-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_pointset-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_simple_dataset-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_fit_reporter-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_fit_result-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_fitter-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_linear_fitter-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_linear_least_squares-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_exv_form_factor-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_form_factor-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_form_factor_type-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_precalculated_exv_form_factor_product-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_precalculated_form_factor_product-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_grid-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_grid_excluded_volume-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_grid_member-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_grid_obj-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_distribution_1d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_distribution_2d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_distribution_3d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_histogram-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_histogram_2d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_distribution_1d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_distribution_2d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_distribution_3d-558dc3e_include.cmake")
include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_entry-558dc3e_include.cmake")
