if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_precalculated_exv_form_factor_product-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_precalculated_exv_form_factor_product-558dc3e_tests.cmake")
else()
  add_test(utest_precalculated_exv_form_factor_product_NOT_BUILT-558dc3e utest_precalculated_exv_form_factor_product_NOT_BUILT-558dc3e)
endif()
