if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_distribution_3d-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_distribution_3d-558dc3e_tests.cmake")
else()
  add_test(utest_distribution_3d_NOT_BUILT-558dc3e utest_distribution_3d_NOT_BUILT-558dc3e)
endif()
