if(EXISTS "/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_entry-558dc3e_tests.cmake")
  include("/home/runner/work/AUSAXS/AUSAXS/_codeql_build_dir/tests/unit/utest_weighted_entry-558dc3e_tests.cmake")
else()
  add_test(utest_weighted_entry_NOT_BUILT-558dc3e utest_weighted_entry_NOT_BUILT-558dc3e)
endif()
