name: DEBUG MAC

on:
- workflow_dispatch

permissions:
  actions: read

jobs: 
  test-shared-lib:
    name: Test shared library
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-and-test.yml
          run_number: 52
          name: ${{ matrix.os }}-binaries

      - name: Test shared library through ctypes
        run: |
          if [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            python3 test/test_shared_lib.py build/lib/libausaxs.so 
          elif [ ${{ matrix.os }} == 'windows-latest' ]; then
            python test/test_shared_lib.py build/bin/ausaxs.dll
          elif [ ${{ matrix.os }} == 'macos-latest' ]; then
            python3 test/test_shared_lib.py build/lib/libausaxs.dylib
          fi