name: Run tests
on: [workflow_dispatch]

#on:
#  push:
#    branches:
#      - master

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install prerequisites
        run: |
          sudo apt-get install libcurl4-openssl-dev
       
      - name: Build the library
        run: |
          mkdir build
          cmake -S . -B build
          cmake -DGUI=OFF --build build --target ausaxs -j $(nproc)
        
      - name: Build tests
        run:
          cmake --build build --target tests -j $(nproc)
          
      - name: Generate test report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'build/test/reports/*.xml'
