name: Run tests
on:
  - workflow_dispatch

permissions:
  - checks: write

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Build the library
        run: |
          mkdir build
          cmake -DGUI=OFF -DCMAKE_BUILD_TYPE=RELEASE -S . -B build
          cmake --build build --target ausaxs -j $(nproc)

      - name: Build the tests
        run: cmake --build build --target tests -j $(nproc)

      - name: Run the tests
        run: ctest --output-on-failure --test-dir build/test

      - name: Generate test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: build/test/reports/*.xml

